### ISSUE TITLE
Wrong Download-Link

### ISSUE THREAD

**Issue by joergotttus** [righter83/checkmk-synology-hyperbackup#1]
Link should point here:
wget https://raw.githubusercontent.com/righter83/checkmk-synology-hyperbackup/main/check_hyperbackup.sh

**Comment by joergotttus** [comment]
Additionally, it chmod +x check_hyperbackup.sh - not .php. ;-)

And just for the files: No longer working with HB 4.1.x - seems, like the newer version of HB doesn't write to /var/log/messages anymore....

**Comment by righter83** [comment]
Hi thanks for the input.
I was too fast with copying.

arr let me check HB 4.1

**Comment by righter83** [comment]
On which DSM are you? I have 7.2-64570
I have only HB 4.0 no update available

**Comment by joergotttus** [comment]
Running DSM 7.2-64570 Update 1; seems like the Central Management System patched Hyper Backup to the “BETA” version (without asking).


Mit freundlichen Grüßen / Best regards

Jörg Ott
Technischer Leiter / Leitung Projekte


Treml & Sturm Datentechnik GmbH
Mühlheimer Straße 209
D-63075 Offenbach am Main
Deutschland/Germany

Telefon: +49 69 - 8990820
Telefax: +49 69 - 89908233

E-Mail: ***@***.******@***.***>
Internet: http://www.treml-sturm.de<http://www.treml-sturm.de/>

Geschäftsführende Gesellschafter:
Johannes Treml und Roland Sturm
Sitz der Gesellschaft: Offenbach am Main
Registergericht: Amtsgericht Offenbach am Main
Registernummer: 5 HRB 10140
USt-ID: DE 182038999

Näheres zur Informationspflicht nach Artikel 13 DS-GVO
und zur Verarbeitung Ihrer personenbezogenen Daten erfahren Sie hier<https://treml-sturm.com/datenschutzhinweise-allgemein/>.

**Comment by righter83** [comment]
yeah it looks like 4.1 is still beta.
I will test it as soon it is published officiallly

**Comment by joergotttus** [comment]
Running DSM 7.2-64570 Update 1; seems like the Central Management System patched Hyper Backup to the “BETA” version (without asking).

**Comment by joergotttus** [comment]
Found the new log location - sufficient to change line 13 to:
message=$(grep "$job_name" /volume1/\@appdata/HyperBackup/log/hyperbackup.log | grep -w 'with result \[[1]\]' | tail -1)

Works with Hyper Backup 4.1.x :-)

**Comment by righter83** [comment]
Ok thanks for the input.

I addedd a version check in 1.1 but cannot test with 4.1 yet :-)

**Comment by joergotttus** [comment]
No problem at all. There's a permission problem right now as @appdata is allowed for root only. And honestly I don't any root-user to be able to connect by SSH keys...

**Comment by righter83** [comment]
Ok My NAS has updated  Hyper Backup to 4.1.0-3716
I tested it with the new log, had to change the grep but is working now
